In [103]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\shubh\onedrive\desktop\data-science\liet_data\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\shubh\onedrive\desktop\data-science\liet_data\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shubh\onedrive\desktop\data-science\liet_data\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\shubh\onedrive\desktop\data-science\liet_data\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\shubh\onedrive\desktop\data-science\liet_data\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [104]:
import pandas as pd
import numpy as np

In [105]:
df=pd.read_csv('Used_Bikes.csv')

In [106]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [108]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [109]:
df.bike_name

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [110]:
df.owner

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [111]:
df.brand

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [112]:
df['brand']

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [113]:
df['owner']

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [114]:
df['city']

0        Ahmedabad
1            Delhi
2            Delhi
3        Bangalore
4        Bangalore
           ...
32643        Delhi
32644       Karnal
32645        Delhi
32646       Jaipur
32647         Pune
Name: city, Length: 32648, dtype: str

In [115]:
df[['owner']]

             owner
0      First Owner
1      First Owner
2      First Owner
3      First Owner
4      First Owner
...            ...
32643  First Owner
32644  First Owner
32645  First Owner
32646  First Owner
32647  First Owner

[32648 rows x 1 columns]

In [116]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [117]:
df[['power']]

       power
0      110.0
1      350.0
2      675.0
3      180.0
4      150.0
...      ...
32643  100.0
32644  180.0
32645  220.0
32646  125.0
32647  150.0

[32648 rows x 1 columns]

In [118]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [119]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [120]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [121]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [122]:
df.tail(12)

,bike_name,price,city,kms_driven,owner,age,power,brand
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [123]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [124]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [125]:
df.duplicated().sum()

np.int64(25324)

In [126]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [127]:
df.duplicated().sum()

np.int64(25324)

In [128]:
df.drop_duplicates(inplace=True)  ####

In [129]:
df.duplicated().sum()

np.int64(0)

In [130]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [131]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [132]:
df.dropna()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [133]:
df.dropna(inplace=True)

In [134]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [135]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [136]:
df['owner'].nunique()

4

In [137]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [138]:
df['brand'].nunique()

23

In [139]:
df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [140]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [141]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [142]:
# df.drop('city',axis=1,inplace=True)

In [143]:
# df.drop(['city','bike_name'], axis= 1 , inplace=True)

In [144]:
char =df.select_dtypes(include='object')

C:\Users\shubh\AppData\Local\Temp\ipykernel_27692\2101896211.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char =df.select_dtypes(include='object')

In [145]:
char

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [146]:
iint=df.select_dtypes(exclude='object')

In [147]:
iint

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [148]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [149]:
df.drop(['city', 'bike_name'], axis=1 , inplace=True)

In [150]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [151]:
df[df['brand']=='Royal Enfield']

         price  kms_driven         owner   age  power          brand
1     119900.0     11000.0   First Owner   4.0  350.0  Royal Enfield
8     145000.0      9190.0   First Owner   3.0  350.0  Royal Enfield
9      88000.0     19000.0  Second Owner   7.0  500.0  Royal Enfield
23    121700.0     24520.0   First Owner   5.0  500.0  Royal Enfield
36     98800.0     39000.0   First Owner   5.0  350.0  Royal Enfield
...        ...         ...           ...   ...    ...            ...
9261  146006.0      8575.0   First Owner   4.0  500.0  Royal Enfield
9319  100000.0     25000.0   First Owner  10.0  350.0  Royal Enfield
9337  120000.0      8492.0   First Owner   5.0  410.0  Royal Enfield
9338  138000.0      5000.0   First Owner   5.0  410.0  Royal Enfield
9344   80000.0     56968.0   First Owner   8.0  350.0  Royal Enfield

[1346 rows x 6 columns]

In [152]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [153]:
df[df['owner']=='First Owner']

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[6642 rows x 6 columns]

In [154]:
# TVS_BIKE =df[df['brand']=='TVS']

In [155]:
# tvs_first_bike =TVS_BIKE[TVS_BIKE['owner']=='First Owner']

In [156]:
# tvs_first_bike[tvs_first_bike['age']<2]

In [157]:
TVS_first_bike =df[(df['brand']=='TVS') & (df['owner']=='First Owner')]

In [158]:

TVS_first_bike

        price  kms_driven        owner   age  power brand
0     35000.0     17654.0  First Owner   3.0  110.0   TVS
3     65000.0     16329.0  First Owner   4.0  180.0   TVS
52    60000.0     30000.0  First Owner   5.0  160.0   TVS
114   69900.0      8700.0  First Owner   3.0  160.0   TVS
130   21500.0     10500.0  First Owner   5.0  125.0   TVS
...       ...         ...          ...   ...    ...   ...
9247  70000.0      4116.0  First Owner   3.0  160.0   TVS
9307  30000.0     30000.0  First Owner  10.0  160.0   TVS
9312  65450.0      9238.0  First Owner   3.0  200.0   TVS
9320  20000.0     84916.0  First Owner  14.0  150.0   TVS
9322  58000.0      4020.0  First Owner   2.0  110.0   TVS

[445 rows x 6 columns]

In [159]:
df.to_csv('clean_bike_data.csv')

In [160]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [161]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [162]:
owner_dict ={
    'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
    
}

In [163]:
df['owner']=df['owner'].map(owner_dict)

In [164]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [165]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       7324 non-null   float64
 1   kms_driven  7324 non-null   float64
 2   owner       7324 non-null   int64
 3   age         7324 non-null   float64
 4   power       7324 non-null   float64
 5   brand       7324 non-null   str
dtypes: float64(4), int64(1), str(1)
memory usage: 400.5 KB

In [166]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [167]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [168]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       7324 non-null   float64
 1   kms_driven  7324 non-null   float64
 2   owner       7324 non-null   int64
 3   age         7324 non-null   float64
 4   power       7324 non-null   float64
 5   brand       7324 non-null   str
dtypes: float64(4), int64(1), str(1)
memory usage: 400.5 KB

In [169]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [170]:
df.rename(columns={'age':'model'})

         price  kms_driven  owner  model  power            brand
0      35000.0     17654.0      1    3.0  110.0              TVS
1     119900.0     11000.0      1    4.0  350.0    Royal Enfield
2     600000.0       110.0      1    8.0  675.0          Triumph
3      65000.0     16329.0      1    4.0  180.0              TVS
4      80000.0     10000.0      1    3.0  150.0           Yamaha
...        ...         ...    ...    ...    ...              ...
9362   25000.0     48587.0      1    8.0  150.0             Hero
9369   35000.0     60000.0      1    9.0  220.0            Bajaj
9370  450000.0      3430.0      1    4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1    4.0  400.0            Bajaj
9372   80000.0      7127.0      1    5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [171]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [172]:
df['brand_encoding']=df['brand'].map(brand_dict)

In [173]:
df.drop('brand_encoding', axis= 1, inplace=True)

In [174]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [175]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}
df['brand']=df['brand'].map(brand_dict)

In [176]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [177]:
x =df.drop('price', axis=1)

In [178]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7324 rows x 5 columns]

In [179]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [180]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [181]:
df.duplicated().sum()

np.int64(18)

In [182]:
df.drop_duplicates(inplace=True)

In [183]:
df.duplicated().sum()

np.int64(0)

In [184]:

df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [185]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [186]:
x =df.drop('price', axis=1)

In [187]:
y =df[['price']]

In [188]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7306 rows x 1 columns]

In [189]:
# df.to_csv('clean_bike.csv')

In [190]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      6
9369     60000.0      1  9.0  220.0      7
9370      3430.0      1  4.0  750.0     15
9371     21300.0      1  4.0  400.0      7
9372      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [191]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7306 rows x 1 columns]

In [192]:
# ! pip install scikit-learn

In [193]:
import sklearn as sns

In [194]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test =train_test_split(x , y , test_size=0.2, random_state= 42)

In [195]:
print(x_train.shape, x_test.shape , y_train.shape ,y_test.shape)

(5844, 5) (1462, 5) (5844, 1) (1462, 1)

In [196]:
x_train

      kms_driven  owner  age  power  brand
8074     12061.0      1  4.0  180.0      1
8930     40000.0      2  7.0  220.0      7
735      28329.0      1  6.0  110.0      6
7922     10000.0      2  8.0  220.0      7
2254     26000.0      1  8.0  150.0      5
...          ...    ...  ...    ...    ...
6532     15383.0      1  2.0  100.0      7
6594     45263.0      1  6.0  150.0      8
6868     45000.0      1  6.0  100.0      6
1028     14836.0      1  8.0  150.0      4
9284      2126.0      1  3.0  250.0      4

[5844 rows x 5 columns]

In [197]:
y_train

         price
8074   65000.0
8930   49000.0
735    32000.0
7922   36000.0
2254   70000.0
...        ...
6532   38000.0
6594   62000.0
6868   30000.0
1028   40000.0
9284  115800.0

[5844 rows x 1 columns]

In [198]:
x_test

      kms_driven  owner   age  power  brand
8955     35000.0      1   9.0  250.0      5
5846      9066.0      1   5.0  250.0     14
8278     48000.0      1  17.0  100.0      6
2461     20222.0      1   5.0  150.0      7
6595     27167.0      1   5.0  150.0      8
...          ...    ...   ...    ...    ...
2588     98971.0      1   8.0  150.0      5
609       2881.0      1   7.0  250.0     14
2283      6517.0      1   2.0  350.0      2
6377      5222.0      1   5.0  350.0      2
647       2980.0      1   6.0  160.0      1

[1462 rows x 5 columns]

In [199]:
y_test

         price
8955  125000.0
5846  220000.0
8278   16900.0
2461   58000.0
6595   58000.0
...        ...
2588   25000.0
609   140000.0
2283  156000.0
6377  118000.0
647    36000.0

[1462 rows x 1 columns]

In [200]:
import joblib

In [201]:
from sklearn.linear_model import LinearRegression
lr =LinearRegression()

In [202]:
lr.fit(x_train, y_train)

LinearRegression()

In [203]:
joblib.dump(lr,"linear_model.lb")

['linear_model.lb']

In [204]:
model.predict(x_test)

NameError: name 'model' is not defined

In [ ]:
x_test

      kms_driven  owner   age  power  brand
8955     35000.0      1   9.0  250.0      5
5846      9066.0      1   5.0  250.0     14
8278     48000.0      1  17.0  100.0      6
2461     20222.0      1   5.0  150.0      7
6595     27167.0      1   5.0  150.0      8
...          ...    ...   ...    ...    ...
2588     98971.0      1   8.0  150.0      5
609       2881.0      1   7.0  250.0     14
2283      6517.0      1   2.0  350.0      2
6377      5222.0      1   5.0  350.0      2
647       2980.0      1   6.0  160.0      1

[1462 rows x 5 columns]

In [ ]:
pred =lr.predict(x_test)

In [ ]:
honda_bike =[[35000.0,	1,	9.0,	250.0,	5]]

In [ ]:
lst =[[9066.0,	1,	5.0,	250.0,	14]]

In [ ]:
lr.predict(lst)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[180558.3983215]])

In [ ]:
lr.predict(honda_bike)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[83929.37665135]])

In [ ]:
pred

array([[ 83929.37665135],
       [180558.3983215 ],
       [-22099.35939509],
       ...,
       [141514.63936524],
       [131317.3298484 ],
       [ 10099.13186722]])

In [ ]:
y_test

         price
8955  125000.0
5846  220000.0
8278   16900.0
2461   58000.0
6595   58000.0
...        ...
2588   25000.0
609   140000.0
2283  156000.0
6377  118000.0
647    36000.0

[1462 rows x 1 columns]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfg =RandomForestRegressor()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
sv = DecisionTreeClassifier(criterion='gini')
sv.get_params()
sv.fit(x_train , y_train)

DecisionTreeClassifier()

In [ ]:
pred=sv.predict(x_test)
pred

array([ 80000., 190000.,  17200., ..., 170000., 139300.,  86900.])

In [ ]:
rfg.fit(x_train, y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [ ]:
x_test

      kms_driven  owner   age  power  brand
8955     35000.0      1   9.0  250.0      5
5846      9066.0      1   5.0  250.0     14
8278     48000.0      1  17.0  100.0      6
2461     20222.0      1   5.0  150.0      7
6595     27167.0      1   5.0  150.0      8
...          ...    ...   ...    ...    ...
2588     98971.0      1   8.0  150.0      5
609       2881.0      1   7.0  250.0     14
2283      6517.0      1   2.0  350.0      2
6377      5222.0      1   5.0  350.0      2
647       2980.0      1   6.0  160.0      1

[1462 rows x 5 columns]

In [ ]:
pred =rfg.predict(x_test)

In [ ]:
pred

array([ 78341.        , 197996.        ,  15205.63      , ...,
       163916.66666667, 112147.        ,  71968.5       ])

In [ ]:
y_test

         price
8955  125000.0
5846  220000.0
8278   16900.0
2461   58000.0
6595   58000.0
...        ...
2588   25000.0
609   140000.0
2283  156000.0
6377  118000.0
647    36000.0

[1462 rows x 1 columns]

In [ ]:
sv.score(x_test , y_test)

0.03898768809849521

In [206]:
model = joblib.load("linear_model.lb")

In [207]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=7)
Mnb=MultinomialNB()
Mnb.fit(x_train,y_train)

MultinomialNB()

In [208]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((120, 4), (120,), (30, 4), (30,))

In [209]:
print("Training Score:",Mnb.score(x_train,y_train))
print("Testing Score:",Mnb.score(x_test,y_test))

Training Score: 0.975
Testing Score: 0.8333333333333334

In [210]:
from sklearn.cluster import KMeans
km =KMeans()

In [212]:
km.fit(x_train,y_train)

KMeans()

In [214]:
print("Training score:-",km.score(x_train,y_train))
print("Testing score:-",km.score(x_test,y_test))

Training score:- -21.757983587104334
Testing score:- -9.02676161880377